2022-01-30T03:36:46,742 Using pip 20.3.4 from /usr/lib/python3/dist-packages/pip (python 3.9)
2022-01-30T03:36:46,743 User install by explicit request
2022-01-30T03:36:46,886 Created temporary directory: /tmp/pip-ephem-wheel-cache-_h1hj4ku
2022-01-30T03:36:46,886 Created temporary directory: /tmp/pip-req-tracker-cmcmfvhy
2022-01-30T03:36:46,887 Initialized build tracking at /tmp/pip-req-tracker-cmcmfvhy
2022-01-30T03:36:46,887 Created build tracker: /tmp/pip-req-tracker-cmcmfvhy
2022-01-30T03:36:46,887 Entered build tracker: /tmp/pip-req-tracker-cmcmfvhy
2022-01-30T03:36:46,888 Created temporary directory: /tmp/pip-install-ykpu8asz
2022-01-30T03:36:46,902 Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
2022-01-30T03:36:46,904 2 location(s) to search for versions of rtmidi-python:
2022-01-30T03:36:46,904 * https://pypi.org/simple/rtmidi-python/
2022-01-30T03:36:46,904 * https://www.piwheels.org/simple/rtmidi-python/
2022-01-30T03:36:46,904 Fetching project page and analyzing links: https://pypi.org/simple/rtmidi-python/
2022-01-30T03:36:46,904 Getting page https://pypi.org/simple/rtmidi-python/
2022-01-30T03:36:46,906 Found index url https://pypi.org/simple
2022-01-30T03:36:46,908 Looking up "https://pypi.org/simple/rtmidi-python/" in the cache
2022-01-30T03:36:46,908 Request header has "max_age" as 0, cache bypassed
2022-01-30T03:36:46,911 Starting new HTTPS connection (1): pypi.org:443
2022-01-30T03:36:46,974 https://pypi.org:443 "GET /simple/rtmidi-python/ HTTP/1.1" 304 0
2022-01-30T03:36:47,040   Found link https://files.pythonhosted.org/packages/d1/70/86e366288c5efef823926a0bfa19fdc90674ea11415f9b19a15894b71994/rtmidi-python-0.2.2.tar.gz#sha256=a092ab3d9b45d43a342a602a60bfd94381dce39d8120f4d06152d7755d57ecf2 (from https://pypi.org/simple/rtmidi-python/), version: 0.2.2
2022-01-30T03:36:47,041   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/18/e1/96b91ea9b79d9af6837ed4ef7af52ba4722b0b42a9e09d8f6acd0209316c/rtmidi-python-0.2.2.win-amd64-py2.7.exe#sha256=1d341334182f4c041da107f109115b2e3a02c5eca961880fc11a664da7b4575d (from https://pypi.org/simple/rtmidi-python/)
2022-01-30T03:36:47,041   Skipping link: unsupported archive format: .exe: https://files.pythonhosted.org/packages/3e/44/552a9cc5ee1e4d9c3f70dbd90504160d6018f90ff511dd3d245b6409f29a/rtmidi-python-0.2.2.win32-py2.7.exe#sha256=20959f5db54338a497d7c9e1821e5845bd1501654f8c59be0129e8c04d14bdbb (from https://pypi.org/simple/rtmidi-python/)
2022-01-30T03:36:47,041 Fetching project page and analyzing links: https://www.piwheels.org/simple/rtmidi-python/
2022-01-30T03:36:47,042 Getting page https://www.piwheels.org/simple/rtmidi-python/
2022-01-30T03:36:47,043 Found index url https://www.piwheels.org/simple
2022-01-30T03:36:47,044 Looking up "https://www.piwheels.org/simple/rtmidi-python/" in the cache
2022-01-30T03:36:47,044 Request header has "max_age" as 0, cache bypassed
2022-01-30T03:36:47,046 Starting new HTTPS connection (1): www.piwheels.org:443
2022-01-30T03:36:47,766 https://www.piwheels.org:443 "GET /simple/rtmidi-python/ HTTP/1.1" 200 290
2022-01-30T03:36:47,769 Updating cache with response from "https://www.piwheels.org/simple/rtmidi-python/"
2022-01-30T03:36:47,769 Caching due to etag
2022-01-30T03:36:47,855   Skipping link: none of the wheel's tags match: cp35-cp35m-linux_armv6l: https://www.piwheels.org/simple/rtmidi-python/rtmidi_python-0.2.2-cp35-cp35m-linux_armv6l.whl#sha256=d1e28f6d40292dab7d9bf782a2dd09e51f9621be27c73f53d01a46d1beaeb8af (from https://www.piwheels.org/simple/rtmidi-python/)
2022-01-30T03:36:47,856   Skipping link: none of the wheel's tags match: cp35-cp35m-linux_armv7l: https://www.piwheels.org/simple/rtmidi-python/rtmidi_python-0.2.2-cp35-cp35m-linux_armv7l.whl#sha256=d1e28f6d40292dab7d9bf782a2dd09e51f9621be27c73f53d01a46d1beaeb8af (from https://www.piwheels.org/simple/rtmidi-python/)
2022-01-30T03:36:47,856   Skipping link: none of the wheel's tags match: cp37-cp37m-linux_armv6l: https://www.piwheels.org/simple/rtmidi-python/rtmidi_python-0.2.2-cp37-cp37m-linux_armv6l.whl#sha256=2ac901aa2c201dc6e5c0378f4150559194a8251f1523bfa524ecedca36ef1495 (from https://www.piwheels.org/simple/rtmidi-python/)
2022-01-30T03:36:47,857   Skipping link: none of the wheel's tags match: cp37-cp37m-linux_armv7l: https://www.piwheels.org/simple/rtmidi-python/rtmidi_python-0.2.2-cp37-cp37m-linux_armv7l.whl#sha256=2ac901aa2c201dc6e5c0378f4150559194a8251f1523bfa524ecedca36ef1495 (from https://www.piwheels.org/simple/rtmidi-python/)
2022-01-30T03:36:47,857 Given no hashes to check 1 links for project 'rtmidi-python': discarding no candidates
2022-01-30T03:36:47,881 Collecting rtmidi-python
2022-01-30T03:36:47,883   Created temporary directory: /tmp/pip-unpack-ibvd5717
2022-01-30T03:36:47,885   Looking up "https://files.pythonhosted.org/packages/d1/70/86e366288c5efef823926a0bfa19fdc90674ea11415f9b19a15894b71994/rtmidi-python-0.2.2.tar.gz" in the cache
2022-01-30T03:36:47,887   Current age based on date: 1236
2022-01-30T03:36:47,887   Ignoring unknown cache-control directive: immutable
2022-01-30T03:36:47,888   Freshness lifetime from max-age: 365000000
2022-01-30T03:36:47,888   The response is "fresh", returning cached response
2022-01-30T03:36:47,888   365000000 > 1236
2022-01-30T03:36:47,889   Using cached rtmidi-python-0.2.2.tar.gz (54 kB)
2022-01-30T03:36:47,905   Added rtmidi-python from https://files.pythonhosted.org/packages/d1/70/86e366288c5efef823926a0bfa19fdc90674ea11415f9b19a15894b71994/rtmidi-python-0.2.2.tar.gz#sha256=a092ab3d9b45d43a342a602a60bfd94381dce39d8120f4d06152d7755d57ecf2 to build tracker '/tmp/pip-req-tracker-cmcmfvhy'
2022-01-30T03:36:47,905     Running setup.py (path:/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py) egg_info for package rtmidi-python
2022-01-30T03:36:47,906     Created temporary directory: /tmp/pip-pip-egg-info-a584s3ae
2022-01-30T03:36:47,906     Running command python setup.py egg_info
2022-01-30T03:36:48,313     running egg_info
2022-01-30T03:36:48,315     creating /tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info
2022-01-30T03:36:48,315     writing /tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/PKG-INFO
2022-01-30T03:36:48,316     writing dependency_links to /tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/dependency_links.txt
2022-01-30T03:36:48,316     writing top-level names to /tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/top_level.txt
2022-01-30T03:36:48,317     writing manifest file '/tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/SOURCES.txt'
2022-01-30T03:36:48,322     reading manifest file '/tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/SOURCES.txt'
2022-01-30T03:36:48,324     writing manifest file '/tmp/pip-pip-egg-info-a584s3ae/rtmidi_python.egg-info/SOURCES.txt'
2022-01-30T03:36:48,371   Source in /tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf has version 0.2.2, which satisfies requirement rtmidi-python from https://files.pythonhosted.org/packages/d1/70/86e366288c5efef823926a0bfa19fdc90674ea11415f9b19a15894b71994/rtmidi-python-0.2.2.tar.gz#sha256=a092ab3d9b45d43a342a602a60bfd94381dce39d8120f4d06152d7755d57ecf2
2022-01-30T03:36:48,372   Removed rtmidi-python from https://files.pythonhosted.org/packages/d1/70/86e366288c5efef823926a0bfa19fdc90674ea11415f9b19a15894b71994/rtmidi-python-0.2.2.tar.gz#sha256=a092ab3d9b45d43a342a602a60bfd94381dce39d8120f4d06152d7755d57ecf2 from build tracker '/tmp/pip-req-tracker-cmcmfvhy'
2022-01-30T03:36:48,375 Created temporary directory: /tmp/pip-unpack-_pqkv4aa
2022-01-30T03:36:48,377 Building wheels for collected packages: rtmidi-python
2022-01-30T03:36:48,379   Created temporary directory: /tmp/pip-wheel-7uc3q5s2
2022-01-30T03:36:48,379   Destination directory: /tmp/pip-wheel-7uc3q5s2
2022-01-30T03:36:48,380   Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-7uc3q5s2
2022-01-30T03:36:48,789   running bdist_wheel
2022-01-30T03:36:48,792   running build
2022-01-30T03:36:48,793   running build_ext
2022-01-30T03:36:48,796   building 'rtmidi_python' extension
2022-01-30T03:36:48,797   creating build
2022-01-30T03:36:48,797   creating build/temp.linux-armv7l-3.9
2022-01-30T03:36:48,798   creating build/temp.linux-armv7l-3.9/RtMidi
2022-01-30T03:36:48,798   arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -I/usr/include/python3.9 -c RtMidi/RtMidi.cpp -o build/temp.linux-armv7l-3.9/RtMidi/RtMidi.o
2022-01-30T03:36:52,879   arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -I/usr/include/python3.9 -c rtmidi_python.cpp -o build/temp.linux-armv7l-3.9/rtmidi_python.o
2022-01-30T03:36:53,933   rtmidi_python.cpp: In function ‘PyObject* PyInit_rtmidi_python()’:
2022-01-30T03:36:53,934   rtmidi_python.cpp:2932:39: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:36:53,934    2932 |   __pyx_type_13rtmidi_python_MidiBase.tp_print = 0;
2022-01-30T03:36:53,934         |                                       ^~~~~~~~
2022-01-30T03:36:53,935   rtmidi_python.cpp:2941:38: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:36:53,935    2941 |   __pyx_type_13rtmidi_python_MidiOut.tp_print = 0;
2022-01-30T03:36:53,936         |                                      ^~~~~~~~
2022-01-30T03:36:53,936   rtmidi_python.cpp:2950:37: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:36:53,936    2950 |   __pyx_type_13rtmidi_python_MidiIn.tp_print = 0;
2022-01-30T03:36:53,937         |                                     ^~~~~~~~
2022-01-30T03:36:53,937   rtmidi_python.cpp:2966:22: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,938    2966 |   PyEval_InitThreads();
2022-01-30T03:36:53,938         |                      ^
2022-01-30T03:36:53,939   In file included from /usr/include/python3.9/Python.h:145,
2022-01-30T03:36:53,939                    from rtmidi_python.cpp:16:
2022-01-30T03:36:53,939   /usr/include/python3.9/ceval.h:130:37: note: declared here
2022-01-30T03:36:53,940     130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
2022-01-30T03:36:53,940         |                                     ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,941   In file included from /usr/include/python3.9/unicodeobject.h:1026,
2022-01-30T03:36:53,941                    from /usr/include/python3.9/Python.h:97,
2022-01-30T03:36:53,941                    from rtmidi_python.cpp:16:
2022-01-30T03:36:53,942   rtmidi_python.cpp: In function ‘int __Pyx_ParseOptionalKeywords(PyObject*, PyObject***, PyObject*, PyObject**, Py_ssize_t, const char*)’:
2022-01-30T03:36:53,942   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,943     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,943         |                                                                           ^
2022-01-30T03:36:53,943   /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,944     261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:36:53,944         |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,945   rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,945    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,946         |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,946   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,946     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,947         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,947   /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,948     262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:36:53,948         |                                                    ^
2022-01-30T03:36:53,948   rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,949    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,949         |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,950   /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:36:53,950     580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:36:53,951         |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,951   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,951     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,952         |                                                                           ^
2022-01-30T03:36:53,952   /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,953     264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:36:53,953         |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,953   rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,954    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,954         |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,955   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,955     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,955         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,956   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,956     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,957         |                                                                           ^
2022-01-30T03:36:53,957   /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,957     261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:36:53,958         |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,958   rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,959    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,959         |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,960   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,960     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,961         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,961   /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,961     262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:36:53,962         |                                                    ^
2022-01-30T03:36:53,962   rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,963    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,963         |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,964   /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:36:53,964     580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:36:53,964         |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,965   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,965     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,966         |                                                                           ^
2022-01-30T03:36:53,966   /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,966     264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:36:53,967         |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,967   rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,968    3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,968         |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,969   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,969     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,969         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,970   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,970     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,971         |                                                                           ^
2022-01-30T03:36:53,971   /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,972     261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:36:53,972         |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,972   rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,973    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,973         |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,974   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,974     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,974         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,975   /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,975     262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:36:53,976         |                                                    ^
2022-01-30T03:36:53,976   rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,977    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,977         |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,977   /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:36:53,978     580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:36:53,978         |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,979   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,979     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,980         |                                                                           ^
2022-01-30T03:36:53,980   /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,980     264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:36:53,981         |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,981   rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,982    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,982         |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,983   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,983     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,984         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,984   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,985     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,985         |                                                                           ^
2022-01-30T03:36:53,985   /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,986     261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:36:53,986         |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,987   rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,987    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,988         |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,988   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,989     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,989         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,990   /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,990     262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:36:53,990         |                                                    ^
2022-01-30T03:36:53,991   rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,991    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,992         |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,992   /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:36:53,993     580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:36:53,993         |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,994   /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:36:53,994     451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:36:53,995         |                                                                           ^
2022-01-30T03:36:53,995   /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:36:53,995     264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:36:53,996         |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,996   rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:36:53,997    3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:36:53,997         |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:36:53,998   /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:36:53,998     446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:36:53,999         |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:36:54,175   error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
2022-01-30T03:36:54,228   ERROR: Failed building wheel for rtmidi-python
2022-01-30T03:36:54,229   Running setup.py clean for rtmidi-python
2022-01-30T03:36:54,230   Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
2022-01-30T03:36:54,623   running clean
2022-01-30T03:36:54,625   removing 'build/temp.linux-armv7l-3.9' (and everything under it)
2022-01-30T03:36:54,626   'build/lib.linux-armv7l-3.9' does not exist -- can't clean it
2022-01-30T03:36:54,626   'build/bdist.linux-armv7l' does not exist -- can't clean it
2022-01-30T03:36:54,627   'build/scripts-3.9' does not exist -- can't clean it
2022-01-30T03:36:54,628   removing 'build'
2022-01-30T03:36:54,671 Failed to build rtmidi-python
2022-01-30T03:36:54,796 Installing collected packages: rtmidi-python
2022-01-30T03:36:54,800   Created temporary directory: /tmp/pip-record-l2hq8kyp
2022-01-30T03:36:54,801     Running command /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2hq8kyp/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.9/rtmidi-python
2022-01-30T03:36:55,198     running install
2022-01-30T03:36:55,201     running build
2022-01-30T03:36:55,201     running build_ext
2022-01-30T03:36:55,206     building 'rtmidi_python' extension
2022-01-30T03:36:55,206     creating build
2022-01-30T03:36:55,206     creating build/temp.linux-armv7l-3.9
2022-01-30T03:36:55,207     creating build/temp.linux-armv7l-3.9/RtMidi
2022-01-30T03:36:55,207     arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -I/usr/include/python3.9 -c RtMidi/RtMidi.cpp -o build/temp.linux-armv7l-3.9/RtMidi/RtMidi.o
2022-01-30T03:36:59,291     arm-linux-gnueabihf-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LINUX_ALSA__ -I/usr/include/python3.9 -c rtmidi_python.cpp -o build/temp.linux-armv7l-3.9/rtmidi_python.o
2022-01-30T03:37:00,349     rtmidi_python.cpp: In function ‘PyObject* PyInit_rtmidi_python()’:
2022-01-30T03:37:00,349     rtmidi_python.cpp:2932:39: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:37:00,349      2932 |   __pyx_type_13rtmidi_python_MidiBase.tp_print = 0;
2022-01-30T03:37:00,350           |                                       ^~~~~~~~
2022-01-30T03:37:00,350     rtmidi_python.cpp:2941:38: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:37:00,351      2941 |   __pyx_type_13rtmidi_python_MidiOut.tp_print = 0;
2022-01-30T03:37:00,351           |                                      ^~~~~~~~
2022-01-30T03:37:00,351     rtmidi_python.cpp:2950:37: error: ‘PyTypeObject’ {aka ‘struct _typeobject’} has no member named ‘tp_print’
2022-01-30T03:37:00,352      2950 |   __pyx_type_13rtmidi_python_MidiIn.tp_print = 0;
2022-01-30T03:37:00,352           |                                     ^~~~~~~~
2022-01-30T03:37:00,353     rtmidi_python.cpp:2966:22: warning: ‘void PyEval_InitThreads()’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,353      2966 |   PyEval_InitThreads();
2022-01-30T03:37:00,353           |                      ^
2022-01-30T03:37:00,354     In file included from /usr/include/python3.9/Python.h:145,
2022-01-30T03:37:00,354                      from rtmidi_python.cpp:16:
2022-01-30T03:37:00,354     /usr/include/python3.9/ceval.h:130:37: note: declared here
2022-01-30T03:37:00,355       130 | Py_DEPRECATED(3.9) PyAPI_FUNC(void) PyEval_InitThreads(void);
2022-01-30T03:37:00,355           |                                     ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,356     In file included from /usr/include/python3.9/unicodeobject.h:1026,
2022-01-30T03:37:00,356                      from /usr/include/python3.9/Python.h:97,
2022-01-30T03:37:00,356                      from rtmidi_python.cpp:16:
2022-01-30T03:37:00,357     rtmidi_python.cpp: In function ‘int __Pyx_ParseOptionalKeywords(PyObject*, PyObject***, PyObject*, PyObject**, Py_ssize_t, const char*)’:
2022-01-30T03:37:00,357     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,358       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,358           |                                                                           ^
2022-01-30T03:37:00,358     /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,359       261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:37:00,359           |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,359     rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,360      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,360           |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,361     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,361       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,361           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,362     /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,362       262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:37:00,363           |                                                    ^
2022-01-30T03:37:00,363     rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,363      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,364           |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,364     /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:37:00,365       580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:37:00,365           |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,365     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,366       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,366           |                                                                           ^
2022-01-30T03:37:00,367     /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,367       264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:37:00,367           |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,368     rtmidi_python.cpp:3094:22: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,368      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,369           |                      ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,369     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,369       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,370           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,370     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,371       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,371           |                                                                           ^
2022-01-30T03:37:00,371     /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,372       261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:37:00,372           |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,372     rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,373      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,373           |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,374     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,374       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,374           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,375     /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,375       262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:37:00,376           |                                                    ^
2022-01-30T03:37:00,376     rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,376      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,377           |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,377     /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:37:00,378       580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:37:00,378           |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,378     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,379       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,379           |                                                                           ^
2022-01-30T03:37:00,379     /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,380       264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:37:00,380           |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,381     rtmidi_python.cpp:3094:52: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,381      3094 |                     (PyUnicode_GET_SIZE(**name) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,382           |                                                    ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,382     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,382       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,383           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,383     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,383       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,384           |                                                                           ^
2022-01-30T03:37:00,384     /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,385       261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:37:00,385           |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,385     rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,386      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,386           |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,387     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,387       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,387           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,388     /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,388       262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:37:00,388           |                                                    ^
2022-01-30T03:37:00,389     rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,389      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,390           |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,390     /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:37:00,390       580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:37:00,391           |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,391     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,392       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,392           |                                                                           ^
2022-01-30T03:37:00,393     /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,393       264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:37:00,393           |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,394     rtmidi_python.cpp:3110:26: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,394      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,394           |                          ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,395     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,395       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,396           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,396     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,396       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,397           |                                                                           ^
2022-01-30T03:37:00,397     /usr/include/python3.9/cpython/unicodeobject.h:261:7: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,398       261 |       PyUnicode_WSTR_LENGTH(op) :                    \
2022-01-30T03:37:00,398           |       ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,398     rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,399      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,399           |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,400     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,400       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,400           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,401     /usr/include/python3.9/cpython/unicodeobject.h:262:52: warning: ‘Py_UNICODE* PyUnicode_AsUnicode(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,401       262 |       ((void)PyUnicode_AsUnicode(_PyObject_CAST(op)),\
2022-01-30T03:37:00,402           |                                                    ^
2022-01-30T03:37:00,402     rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,403      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,403           |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,403     /usr/include/python3.9/cpython/unicodeobject.h:580:45: note: declared here
2022-01-30T03:37:00,404       580 | Py_DEPRECATED(3.3) PyAPI_FUNC(Py_UNICODE *) PyUnicode_AsUnicode(
2022-01-30T03:37:00,404           |                                             ^~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,405     /usr/include/python3.9/cpython/unicodeobject.h:451:75: warning: ‘Py_ssize_t _PyUnicode_get_wstr_length(PyObject*)’ is deprecated [-Wdeprecated-declarations]
2022-01-30T03:37:00,405       451 | #define PyUnicode_WSTR_LENGTH(op) _PyUnicode_get_wstr_length((PyObject*)op)
2022-01-30T03:37:00,405           |                                                                           ^
2022-01-30T03:37:00,406     /usr/include/python3.9/cpython/unicodeobject.h:264:8: note: in expansion of macro ‘PyUnicode_WSTR_LENGTH’
2022-01-30T03:37:00,406       264 |        PyUnicode_WSTR_LENGTH(op)))
2022-01-30T03:37:00,407           |        ^~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,407     rtmidi_python.cpp:3110:59: note: in expansion of macro ‘PyUnicode_GET_SIZE’
2022-01-30T03:37:00,408      3110 |                         (PyUnicode_GET_SIZE(**argname) != PyUnicode_GET_SIZE(key)) ? 1 :
2022-01-30T03:37:00,408           |                                                           ^~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,408     /usr/include/python3.9/cpython/unicodeobject.h:446:26: note: declared here
2022-01-30T03:37:00,409       446 | static inline Py_ssize_t _PyUnicode_get_wstr_length(PyObject *op) {
2022-01-30T03:37:00,409           |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
2022-01-30T03:37:00,592     error: command '/usr/bin/arm-linux-gnueabihf-gcc' failed with exit code 1
2022-01-30T03:37:00,643 ERROR: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2hq8kyp/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.9/rtmidi-python Check the logs for full command output.
2022-01-30T03:37:00,644 Exception information:
2022-01-30T03:37:00,644 Traceback (most recent call last):
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 848, in install
2022-01-30T03:37:00,644     success = install_legacy(
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/operations/install/legacy.py", line 86, in install
2022-01-30T03:37:00,644     raise LegacyInstallFailure
2022-01-30T03:37:00,644 pip._internal.operations.install.legacy.LegacyInstallFailure
2022-01-30T03:37:00,644 
2022-01-30T03:37:00,644 During handling of the above exception, another exception occurred:
2022-01-30T03:37:00,644 
2022-01-30T03:37:00,644 Traceback (most recent call last):
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/cli/base_command.py", line 223, in _main
2022-01-30T03:37:00,644     status = self.run(options, args)
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
2022-01-30T03:37:00,644     return func(self, options, args)
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/commands/install.py", line 421, in run
2022-01-30T03:37:00,644     installed = install_given_reqs(
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/req/__init__.py", line 82, in install_given_reqs
2022-01-30T03:37:00,644     requirement.install(
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/req/req_install.py", line 866, in install
2022-01-30T03:37:00,644     six.reraise(*exc.parent)
2022-01-30T03:37:00,644   File "/usr/share/python-wheels/six-1.16.0-py2.py3-none-any.whl/six.py", line 719, in reraise
2022-01-30T03:37:00,644     raise value
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/operations/install/legacy.py", line 74, in install
2022-01-30T03:37:00,644     runner(
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 292, in runner
2022-01-30T03:37:00,644     call_subprocess(
2022-01-30T03:37:00,644   File "/usr/lib/python3/dist-packages/pip/_internal/utils/subprocess.py", line 261, in call_subprocess
2022-01-30T03:37:00,644     raise InstallationSubprocessError(proc.returncode, command_desc)
2022-01-30T03:37:00,644 pip._internal.exceptions.InstallationSubprocessError: Command errored out with exit status 1: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ykpu8asz/rtmidi-python_5e2036bb9915431a80d4e0ad17b72fbf/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-l2hq8kyp/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.9/rtmidi-python Check the logs for full command output.
2022-01-30T03:37:00,655 Removed build tracker: '/tmp/pip-req-tracker-cmcmfvhy'
